# Generated by Django 6.0.6 on 2026-06-17 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('nif', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('poblacion', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=50)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.cliente')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
            ],
        ),
        migrations.CreateModel(
            name='ParteReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField()),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En Diagnóstico'), ('esperando', 'Esperando Repuesto'), ('reparado', 'Reparado'), ('entregado', 'Entregado')], default='recibido', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('descripcion_tecnico', models.TextField(blank=True, null=True)),
                ('horas_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_hora', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('stock_procesado', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.equipo')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_piezas', to='reparaciones.partereparacion')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.pieza')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
            ],
        ),
        migrations.AddField(
            model_name='pieza',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importe_entregado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.cliente')),
                ('parte_reparacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reparaciones.partereparacion')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.pieza')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_extras', to='reparaciones.venta')),
            ],
        ),
    ]
