# Generated by Django 6.0.6 on 2026-06-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='nif',
            field=models.CharField(default=1, max_length=20, verbose_name='CIF/NIF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
