# Generated by Django 6.0.6 on 2026-06-17 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_taller_nif_taller_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('efectivo_apertura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_cierre_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
            ],
        ),
    ]
